### ISSUE TITLE
Vigem Bus instead of vjoy?

### ISSUE THREAD

**Issue by Trihy** [Geekonarium/LichtknarrePlugin#3]
Hi. This is not a bug report, but since discussion is not avaiblabe, just opened here.

Wonder if vigem support to emulate xbox 360 controllers wont be a better option than vjoy.

Im a frequent user of touchmote, and there are some builds with vigem bus. It works pretty fine for emulators like mame and many others. IR can emulate right or left stick. And also you could have easy access to emulate other buttons for any other type of game.

https://github.com/ViGEm/ViGEmBus

**Comment by Geekonarium** [comment]
Hi im working already on a Xinput hook connector plugin:

https://docs.google.com/document/d/1_hO48IkGl4tYwfkDmiX3Pz3olSzyAhgVJpxdv0QwmsE/edit

Works for Dolphin 4 so far. Raw-Input will follow. Also bought some xbox 360 controller to know what to hook with which data.

But will take some time. 

Will have a look on ViGEmBus. If licences works for me will consider to use it maybe. Thanks for the info :-)

Also a ton of other features are planned. Have a look here:
https://geekonarium.de/en/download-changelog-lightgun-lichtknarre-wiimote-line-of-sight-pc-windows/#commingsoon

**Comment by Trihy** [comment]
Hi. Thanks for your answer. Great to know it´s a wip. Vigem handles rumble great, (I read there are some problems with vjoy)

I read about a discord server but couldnt find it.

Just a few ideas, permanently pair wiimotes could be easily done https://www.richlynch.com/2009/11/18/permanently-pair-wiimotewii-balance-board/ or https://github.com/jordanbtucker/WiiPair

So once paired with the sync button, you can press any button to reconnect. Some routines are updated for TR ones. Every new wiimote is a TR one if you are trying to find one. 

And are we able to send sound with wiimotelib? Would be a great solution to send gun or custom sound every time a button press.

If you need testing with TR ones, just ask. I have a TR one and a UB400 dongle.

There are some vigem builds of touchmote here https://github.com/simphax/Touchmote/issues/65, just go to the bottom, if you want to check for code there is also a newer repo. Also the pairing routine could be useful. Touchmote once paired with sync button, will reconnect pressing just a button, even if reboot or turned off the system.

**Comment by Geekonarium** [comment]
This works already. Hold 1 and 2 till its connected as described in the description of the tool. If you have problems with this than you have another problem. Consider viewing the troubleshooting guide:

https://geekonarium.de/en/lichtknarre-lightgun-wii-4-led-tracker-plugin/#troubleshooting

**Comment by Geekonarium** [comment]
You find Discord here: https://geekonarium.de/en/lightgun-lichtknarre-about-the-plugin-system/#devcommunity

**Comment by Geekonarium** [comment]
https://github.com/simphax/Touchmote/issues/65 << thanks for info

**Comment by Trihy** [comment]
Hi. You mean the TR ones? I could pair a non TR one, still didnt tried with a TR one.

Edit. Tried, TR ones works too.

But permanently pairing works a little better, once paired there is no need to hold sync or 1+2 again. Both options triggers a new pairing routine instead of using the already paired on bluetooth enumerator. With the permanently you can press A, B, up, down, any button and will reconnect.

**Comment by Geekonarium** [comment]
For me permanent pairing didn't worked after shutting down wii.

**Comment by Geekonarium** [comment]
Lets speak on Discord. Will close this issue.

**Comment by Trihy** [comment]
Thats weird. You can give it a try to touchmote to see how permanent pairing work, you press pair wiimotes, hit sync button Then you can close touchmote, restart the computer, just open tmote again hit any button on wiimote and will connect. I think wiimotehook does that too, but dont remember atm.
 
Some emulators like retroarch could see like another controller if you press 1+2 every time wiimote disconnects. turn off by accident, etc.

Will go to discord to see if I can help
